version: '3.8'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=10000
    command: >-
      etcd -advertise-client-urls=http://0.0.0.0:2379
           -listen-client-urls=http://0.0.0.0:2379
           -listen-peer-urls=http://0.0.0.0:2380
           -initial-advertise-peer-urls=http://0.0.0.0:2380
           -initial-cluster=default=http://0.0.0.0:2380
           -initial-cluster-token=etcd-cluster
           -initial-cluster-state=new
    volumes:
      - etcd_data:/etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 12

  minio:
    image: minio/minio:RELEASE.2024-07-26T20-48-21Z
    container_name: milvus-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address :9090
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # Console UI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 12

  milvus:
    image: milvusdb/milvus:v2.4.8
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MILVUS_LOG_LEVEL=info
    ulimits:
      nofile:
        soft: 524288
        hard: 524288
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "19530:19530"   # gRPC
      - "9091:9091"     # REST
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  milvus_data:
  etcd_data:
  minio_data:
